version: "3.9"

services:
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot:/root
      - ./dbroot/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "28432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5

  java:
    build: ./javaroot
    restart: unless-stopped
    depends_on:
      - postgres
    command: sh -c "/wait && java -jar GotoBankOnlineJavaTgBot.jar"
    volumes:
      - ./javaroot:/root
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres